server:
  port: 8079
  
custom:
  services:
    location:
      base-url: http://location-service

spring:
  application:
    name: person-service
  datasource:
    url: jdbc:h2:file:./data/persondb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

